#!/usr/bin/env python3
"""Embed the checked-in PNG as a deterministic C++ byte array."""
from pathlib import Path

root = Path(__file__).resolve().parents[1]
source = root / "UI" / "fuimadane_wave_bg.png"
target = root / "ArtworkData.hpp"
data = source.read_bytes()
if not data.startswith(b"\x89PNG\r\n\x1a\n"):
    raise SystemExit(f"Not a PNG: {source}")
rows = [
    "    " + ", ".join(f"0x{byte:02x}" for byte in data[i:i + 16]) + ","
    for i in range(0, len(data), 16)
]
target.write_text(
    "#pragma once\n"
    "// Generated by tools/embed-artwork.py from UI/fuimadane_wave_bg.png.\n"
    "inline constexpr unsigned char kDrumCloudWaveBgPng[] = {\n"
    + "\n".join(rows)
    + "\n};\n",
    encoding="utf-8",
)
print(f"Embedded {len(data)} PNG bytes in {target.name}")
